### ISSUE TITLE
Criar Logo do Aplicativo

### ISSUE THREAD

**Issue by Man0Lulu** [Man0Lulu/Pi---mobile#7]

**Comment by DaviAtrock** [comment]
![Logo1](https://github.com/Man0Lulu/Pi---mobile/assets/103908152/9ce21dbf-9a45-46c5-a045-6ab671c613b3)
![Logo2](https://github.com/Man0Lulu/Pi---mobile/assets/103908152/eb0ecd89-4c49-4e0e-b22f-f210b9d86ca5)
![Logo3](https://github.com/Man0Lulu/Pi---mobile/assets/103908152/ee13b601-edfc-49ea-bd93-1d5a02e3126a)
